package GUI;

import Logica.Procesos;
import javax.swing.JOptionPane;

public class Principal extends javax.swing.JFrame {

    Procesos procesos = null; 
    
    public Principal() {
        procesos = new Procesos();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblUno = new javax.swing.JLabel();
        lblTres = new javax.swing.JLabel();
        lblSeis = new javax.swing.JLabel();
        lblNueve = new javax.swing.JLabel();
        lblDoce = new javax.swing.JLabel();
        txtUno = new javax.swing.JTextField();
        txtTres = new javax.swing.JTextField();
        txtDoce = new javax.swing.JTextField();
        txtNueve = new javax.swing.JTextField();
        txtSeis = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        txtMontoUno = new javax.swing.JTextField();
        txtMontoTres = new javax.swing.JTextField();
        txtMontoSeis = new javax.swing.JTextField();
        txtMontoNueve = new javax.swing.JTextField();
        txtMontoDoce = new javax.swing.JTextField();
        txtTotalUno = new javax.swing.JTextField();
        txtTotalTres = new javax.swing.JTextField();
        txtTotalSeis = new javax.swing.JTextField();
        txtTotalNueve = new javax.swing.JTextField();
        txtTotalDoce = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtMontoContado = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Calculadora de % Cuota$");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 51)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        lblUno.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblUno.setForeground(new java.awt.Color(255, 255, 255));
        lblUno.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblUno.setText("1 Pago con T. Credito:");

        lblTres.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblTres.setForeground(new java.awt.Color(255, 255, 255));
        lblTres.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTres.setText("3 Pagos con T. Credito:");

        lblSeis.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblSeis.setForeground(new java.awt.Color(255, 255, 255));
        lblSeis.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSeis.setText("6 Pagos con T. Credito:");

        lblNueve.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblNueve.setForeground(new java.awt.Color(255, 255, 255));
        lblNueve.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNueve.setText("9 Pagos con T. Credito:");

        lblDoce.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblDoce.setForeground(new java.awt.Color(255, 255, 255));
        lblDoce.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDoce.setText("12 Pagos con T. Credito:");

        txtUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUnoActionPerformed(evt);
            }
        });

        txtTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTresActionPerformed(evt);
            }
        });

        txtDoce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDoceActionPerformed(evt);
            }
        });

        txtNueve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNueveActionPerformed(evt);
            }
        });

        txtSeis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSeisActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Cant. de Cuotas");

        jLabel8.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Monto por cuota");

        jLabel9.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Total");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtMontoUno.setEditable(false);
        txtMontoUno.setBackground(new java.awt.Color(255, 255, 255));
        txtMontoUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMontoUnoActionPerformed(evt);
            }
        });

        txtMontoTres.setEditable(false);
        txtMontoTres.setBackground(new java.awt.Color(255, 255, 255));

        txtMontoSeis.setEditable(false);
        txtMontoSeis.setBackground(new java.awt.Color(255, 255, 255));

        txtMontoNueve.setEditable(false);
        txtMontoNueve.setBackground(new java.awt.Color(255, 255, 255));

        txtMontoDoce.setEditable(false);
        txtMontoDoce.setBackground(new java.awt.Color(255, 255, 255));

        txtTotalUno.setEditable(false);
        txtTotalUno.setBackground(new java.awt.Color(255, 255, 255));
        txtTotalUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalUnoActionPerformed(evt);
            }
        });

        txtTotalTres.setEditable(false);
        txtTotalTres.setBackground(new java.awt.Color(255, 255, 255));
        txtTotalTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalTresActionPerformed(evt);
            }
        });

        txtTotalSeis.setEditable(false);
        txtTotalSeis.setBackground(new java.awt.Color(255, 255, 255));
        txtTotalSeis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalSeisActionPerformed(evt);
            }
        });

        txtTotalNueve.setEditable(false);
        txtTotalNueve.setBackground(new java.awt.Color(255, 255, 255));
        txtTotalNueve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalNueveActionPerformed(evt);
            }
        });

        txtTotalDoce.setEditable(false);
        txtTotalDoce.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Monto Contado:");

        txtMontoContado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMontoContadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMontoContado, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblSeis)
                            .addComponent(lblNueve)
                            .addComponent(lblDoce)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(221, 221, 221)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDoce, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNueve, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSeis, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(lblUno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtUno, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(lblTres)
                                .addGap(18, 18, 18)
                                .addComponent(txtTres, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtMontoNueve, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtMontoSeis, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtMontoTres, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtMontoUno, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtMontoDoce, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtTotalNueve)
                            .addComponent(txtTotalSeis, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTotalTres, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTotalUno, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                            .addComponent(txtTotalDoce))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(txtMontoContado, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(txtTotalUno, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(txtTotalTres, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTotalSeis, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTotalNueve, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTotalDoce, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtMontoUno, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMontoTres, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMontoSeis, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMontoNueve, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMontoDoce, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUno, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUno, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lblTres, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(lblSeis, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(lblNueve, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblDoce, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(37, 37, 37)
                                                .addComponent(txtDoce, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(37, 37, 37)
                                        .addComponent(txtNueve, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txtTres, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSeis, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6))
        );

        jButton1.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        jButton1.setText("Calcular");
        jButton1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 10, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(357, 357, 357))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTotalNueveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalNueveActionPerformed
        
    }//GEN-LAST:event_txtTotalNueveActionPerformed

    private void txtTotalTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalTresActionPerformed
        
    }//GEN-LAST:event_txtTotalTresActionPerformed

    private void txtTotalSeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalSeisActionPerformed
        
    }//GEN-LAST:event_txtTotalSeisActionPerformed

    private void txtMontoContadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMontoContadoActionPerformed
       
    }//GEN-LAST:event_txtMontoContadoActionPerformed

    private void txtUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUnoActionPerformed
        
    }//GEN-LAST:event_txtUnoActionPerformed

    private void txtTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTresActionPerformed
        
    }//GEN-LAST:event_txtTresActionPerformed

    private void txtSeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSeisActionPerformed
        
    }//GEN-LAST:event_txtSeisActionPerformed

    private void txtNueveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNueveActionPerformed
        
    }//GEN-LAST:event_txtNueveActionPerformed

    private void txtDoceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDoceActionPerformed
        
    }//GEN-LAST:event_txtDoceActionPerformed

    private void txtMontoUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMontoUnoActionPerformed
        
    }//GEN-LAST:event_txtMontoUnoActionPerformed

    private void txtTotalUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalUnoActionPerformed

        
    }//GEN-LAST:event_txtTotalUnoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String montoContado = txtMontoContado.getText();
        try{
            if (!montoContado.isEmpty()){
                int contado = Integer.parseInt(montoContado);
            
                //EN UNA SOLA CUOTA
                String unaCuota = txtUno.getText();
                if (!unaCuota.isEmpty()){
                    int cuotaUno = Integer.parseInt(unaCuota);
                        //TOTAL FINAL
                    procesos.setValor(contado);
                    procesos.setPorcentaje(cuotaUno);
                    procesos.calcularTotal();
                    txtTotalUno.setText(String.format("%.2f",procesos.getTotal()));
                        //MONTO POR CUOTA
                    procesos.setCantCuota(1);
                    procesos.valorCuota();  // Calcula el monto por cuota
                    txtMontoUno.setText(String.format("%.2f",procesos.getMontoCuota()));
                        

                }
                
                //EN TRES CUOTAS
                String tresCuotas = txtTres.getText();                 
                    
                if (!tresCuotas.isEmpty()){
                    int cuotaTres = Integer.parseInt(tresCuotas);
                    procesos.setValor(contado);
                    procesos.setPorcentaje(cuotaTres);
                    procesos.calcularTotal();
                    txtTotalTres.setText(String.format("%.2f",procesos.getTotal()));
                    //MONTO POR CUOTA
                    procesos.setCantCuota(3);
                    procesos.valorCuota();  // Calcula el monto por cuota
                    txtMontoTres.setText(String.format("%.2f",procesos.getMontoCuota()));
                }
                
                //EN SEIS CUOTAS
                String seisCuotas = txtSeis.getText();
                if (!seisCuotas.isEmpty()){
                    int cuotaSeis = Integer.parseInt(seisCuotas);
                    procesos.setValor(contado);
                    procesos.setPorcentaje(cuotaSeis);
                    procesos.calcularTotal();
                    txtTotalSeis.setText(String.format("%.2f",procesos.getTotal()));
                    //MONTO POR CUOTA\
                    procesos.setCantCuota(6);
                    procesos.valorCuota();  // Calcula el monto por cuota
                    txtMontoSeis.setText(String.format("%.2f",procesos.getMontoCuota()));
                }
                
                //EN NUEVE CUOTAS
                String nueveCuotas = txtNueve.getText();
                if (!nueveCuotas.isEmpty()){
                    int cuotaNueve = Integer.parseInt(nueveCuotas);
                    procesos.setValor(contado);
                    procesos.setPorcentaje(cuotaNueve);
                    procesos.calcularTotal();
                    txtTotalNueve.setText(String.format("%.2f",procesos.getTotal()));
                    //MONTO POR CUOTA
                    procesos.setCantCuota(9);
                    procesos.valorCuota();  // Calcula el monto por cuota
                    txtMontoNueve.setText(String.format("%.2f",procesos.getMontoCuota()));
                }
                //EN DOCE CUOTAS
                String doceCuotas = txtDoce.getText();
                if (!doceCuotas.isEmpty()){
                    int cuotaDoce = Integer.parseInt(doceCuotas);
                    procesos.setValor(contado);
                    procesos.setPorcentaje(cuotaDoce);
                    procesos.calcularTotal();
                    txtTotalDoce.setText(String.format("%.2f",procesos.getTotal()));
                    //MONTO POR CUOTA
                    procesos.setCantCuota(12);
                    procesos.valorCuota();  // Calcula el monto por cuota
                    txtMontoDoce.setText(String.format("%.2f",procesos.getMontoCuota()));
                } else {
                    JOptionPane.showMessageDialog(null, "Por favor ingrese un valor válido en el campo de monto contado.");
        }
            }
        }catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Por favor ingrese valores numéricos válidos en los campos.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblDoce;
    private javax.swing.JLabel lblNueve;
    private javax.swing.JLabel lblSeis;
    private javax.swing.JLabel lblTres;
    private javax.swing.JLabel lblUno;
    private javax.swing.JTextField txtDoce;
    private javax.swing.JTextField txtMontoContado;
    private javax.swing.JTextField txtMontoDoce;
    private javax.swing.JTextField txtMontoNueve;
    private javax.swing.JTextField txtMontoSeis;
    private javax.swing.JTextField txtMontoTres;
    private javax.swing.JTextField txtMontoUno;
    private javax.swing.JTextField txtNueve;
    private javax.swing.JTextField txtSeis;
    private javax.swing.JTextField txtTotalDoce;
    private javax.swing.JTextField txtTotalNueve;
    private javax.swing.JTextField txtTotalSeis;
    private javax.swing.JTextField txtTotalTres;
    private javax.swing.JTextField txtTotalUno;
    private javax.swing.JTextField txtTres;
    private javax.swing.JTextField txtUno;
    // End of variables declaration//GEN-END:variables
}